### ISSUE TITLE
Examples aren't up-to-date in 0.2.3

### ISSUE THREAD

**Issue by jajetloh** [asynchronics/asynchronix#42]
Was looking around some of the examples in the repo, but when copying them into my project using 0.2.3, noticed that for example, [power_supply.rs](https://github.com/asynchronics/asynchronix/blob/main/asynchronix/examples/power_supply.rs) uses ``.connect_sink()``, which seems to me like it should now use ``.connect_slot()``. Not sure if it's because I'm not using a dev branch or so, but seems broken for me.

At the same time - I managed to get the power_supply example working for me, so would there be interest if say, I made a PR with fixes for the example files? Is this something worth doing at this point?

**Comment by sbarral** [comment]
Closing for now, but feel free to re-open if you have suggestions on how to make this a little less confusing.

**Comment by jajetloh** [comment]
Apologies for the delay, thanks for clarifying! Am very new myself as to what best practices are for building libraries so no suggestions on my end, but great to hear that the issue was just looking at the wrong branch!
