### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshburkart** [asynchronics/asynchronix#49]
Hi there! I'm curious when a new release might be coming out? We'd prefer only to depend on releases, but there are some features in `main` that we'd love to have. (Specifically a `clone`-able scheduler.)

**Comment by sbarral** [comment]
This prompted me to write a dedicated [tracking issue](#50 ) with tentative deadlines etc.

If you need this specific feature earlier, it should not be too hard to backport it to `v0.2` so I would be happy to take a PR.

Closing in favor of #50.

**Comment by sbarral** [comment]
Heads-up: `0.3.0-beta.0` is out!
